#!/usr/bin/env node
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const kb = (value) => Math.round(value * 1024);
const formatKb = (value) => `${(value / 1024).toFixed(2)} KB`;
const args = process.argv.slice(2);
const readArg = (name) => {
  const prefix = `--${name}=`;
  return args.find((arg) => arg.startsWith(prefix))?.slice(prefix.length);
};

const targets = [
  {
    id: "light",
    name: "elfui (light: reactivity + runtime public API, no compiler)",
    entry: resolve(root, "packages/elfui/src/index.ts"),
    target: kb(10.7)
  },
  {
    id: "runtime",
    name: "@elfui/runtime (stable runtime API, no compiler)",
    entry: resolve(root, "packages/runtime/src/index.ts"),
    target: kb(13)
  },
  {
    id: "reactivity",
    name: "@elfui/reactivity (reactivity only)",
    entry: resolve(root, "packages/reactivity/src/index.ts"),
    target: kb(4.3)
  }
];

const buildSize = async (target, minify) => {
  const result = await build({
    entryPoints: [target.entry],
    bundle: true,
    format: "esm",
    minify,
    treeShaking: true,
    write: false,
    external: [],
    platform: "browser",
    legalComments: "none",
    define: { __DEV__: "false" }
  });
  return result.outputFiles[0].contents;
};

const results = [];

for (const target of targets) {
  const min = await buildSize(target, true);
  const raw = await buildSize(target, false);
  results.push({
    id: target.id,
    name: target.name,
    raw: raw.byteLength,
    min: min.byteLength,
    gz: gzipSync(min, { level: 9 }).byteLength,
    target: target.target
  });
}

console.log("\n📦 ElfUI size report\n");
for (const result of results) {
  const ok = result.gz <= result.target;
  console.log(`${ok ? "✅" : "⚠️"} ${result.name}`);
  console.log(`   raw : ${formatKb(result.raw)}`);
  console.log(`   min : ${formatKb(result.min)}`);
  console.log(`   gzip: ${formatKb(result.gz)} / target ${(result.target / 1024).toFixed(1)} KB`);
}

const baselinePath = readArg("baseline");
const baseline = baselinePath
  ? JSON.parse(await readFile(resolve(root, baselinePath), "utf8"))
  : undefined;
const baselineById = new Map((baseline?.targets ?? []).map((item) => [item.id, item]));
const reportPath = readArg("report");

if (reportPath) {
  const { format } = await import("prettier");
  const now = new Date().toISOString();
  const lines = [
    "# ElfUI Size Report",
    "",
    `> Generated by \`npm run size:report\` on ${now}.`,
    "",
    "## Current Budget",
    "",
    "| Target | Raw | Min | Gzip | Budget | Status | Diff From Baseline |",
    "| --- | ---: | ---: | ---: | ---: | --- | ---: |"
  ];
  for (const result of results) {
    const prev = baselineById.get(result.id);
    const diff = prev ? result.gz - prev.gz : undefined;
    const diffText =
      diff === undefined ? "-" : `${diff >= 0 ? "+" : ""}${(diff / 1024).toFixed(2)} KB`;
    lines.push(
      `| ${result.name} | ${formatKb(result.raw)} | ${formatKb(result.min)} | ${formatKb(result.gz)} | ${(result.target / 1024).toFixed(1)} KB | ${result.gz <= result.target ? "pass" : "fail"} | ${diffText} |`
    );
  }
  if (baseline) {
    lines.push(
      "",
      "## Baseline",
      "",
      `Baseline: ${baseline.label}`,
      "",
      "| Target | Baseline Gzip |",
      "| --- | ---: |"
    );
    for (const item of baseline.targets) {
      lines.push(`| ${item.name} | ${formatKb(item.gz)} |`);
    }
  }
  lines.push("");
  const markdown = await format(lines.join("\n"), { parser: "markdown" });
  await writeFile(resolve(root, reportPath), markdown, "utf8");
}

const failed = results.filter((result) => result.gz > result.target);
if (failed.length > 0) {
  for (const result of failed) {
    console.error(
      `size exceeded: ${result.name} gzip ${formatKb(result.gz)} > ${(result.target / 1024).toFixed(1)} KB`
    );
  }
  process.exit(1);
}
